//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Regenerate with: make generate
// (requires controller-gen installed: go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest)

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ── DynatraceSLO ──────────────────────────────────────────────────────────

func (in *DynatraceSLO) DeepCopyInto(out *DynatraceSLO) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DynatraceSLO) DeepCopy() *DynatraceSLO {
	if in == nil {
		return nil
	}
	out := new(DynatraceSLO)
	in.DeepCopyInto(out)
	return out
}

func (in *DynatraceSLO) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynatraceSLOList) DeepCopyInto(out *DynatraceSLOList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynatraceSLO, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DynatraceSLOList) DeepCopy() *DynatraceSLOList {
	if in == nil {
		return nil
	}
	out := new(DynatraceSLOList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynatraceSLOList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynatraceSLOSpec) DeepCopyInto(out *DynatraceSLOSpec) {
	*out = *in
	out.ServiceSelector = in.ServiceSelector
	if in.Warning != nil {
		x := *in.Warning
		out.Warning = &x
	}
	if in.LatencyThresholdMs != nil {
		x := *in.LatencyThresholdMs
		out.LatencyThresholdMs = &x
	}
}

func (in *DynatraceSLOStatus) DeepCopyInto(out *DynatraceSLOStatus) {
	*out = *in
	if in.CurrentValue != nil {
		x := *in.CurrentValue
		out.CurrentValue = &x
	}
	if in.ErrorBudgetRemaining != nil {
		x := *in.ErrorBudgetRemaining
		out.ErrorBudgetRemaining = &x
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ServiceSelector) DeepCopyInto(out *ServiceSelector) { *out = *in }

// ── DynatraceAlert ────────────────────────────────────────────────────────

func (in *DynatraceAlert) DeepCopyInto(out *DynatraceAlert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DynatraceAlert) DeepCopy() *DynatraceAlert {
	if in == nil {
		return nil
	}
	out := new(DynatraceAlert)
	in.DeepCopyInto(out)
	return out
}

func (in *DynatraceAlert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynatraceAlertList) DeepCopyInto(out *DynatraceAlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynatraceAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DynatraceAlertList) DeepCopy() *DynatraceAlertList {
	if in == nil {
		return nil
	}
	out := new(DynatraceAlertList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynatraceAlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynatraceAlertSpec) DeepCopyInto(out *DynatraceAlertSpec) {
	*out = *in
	out.ServiceSelector = in.ServiceSelector
	if in.SLORef != nil {
		x := *in.SLORef
		out.SLORef = &x
	}
	if in.AlertingProfileRef != nil {
		x := *in.AlertingProfileRef
		out.AlertingProfileRef = &x
	}
}

func (in *DynatraceAlertStatus) DeepCopyInto(out *DynatraceAlertStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// ── DynatraceDashboard ────────────────────────────────────────────────────

func (in *DynatraceDashboard) DeepCopyInto(out *DynatraceDashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DynatraceDashboard) DeepCopy() *DynatraceDashboard {
	if in == nil {
		return nil
	}
	out := new(DynatraceDashboard)
	in.DeepCopyInto(out)
	return out
}

func (in *DynatraceDashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynatraceDashboardList) DeepCopyInto(out *DynatraceDashboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynatraceDashboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DynatraceDashboardList) DeepCopy() *DynatraceDashboardList {
	if in == nil {
		return nil
	}
	out := new(DynatraceDashboardList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynatraceDashboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynatraceDashboardSpec) DeepCopyInto(out *DynatraceDashboardSpec) {
	*out = *in
	out.ServiceSelector = in.ServiceSelector
	if in.SLORefs != nil {
		in, out := &in.SLORefs, &out.SLORefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *DynatraceDashboardStatus) DeepCopyInto(out *DynatraceDashboardStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// ── DynatraceNotification ─────────────────────────────────────────────────

func (in *DynatraceNotification) DeepCopyInto(out *DynatraceNotification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DynatraceNotification) DeepCopy() *DynatraceNotification {
	if in == nil {
		return nil
	}
	out := new(DynatraceNotification)
	in.DeepCopyInto(out)
	return out
}

func (in *DynatraceNotification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DynatraceNotificationList) DeepCopyInto(out *DynatraceNotificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynatraceNotification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DynatraceNotificationList) DeepCopy() *DynatraceNotificationList {
	if in == nil {
		return nil
	}
	out := new(DynatraceNotificationList)
	in.DeepCopyInto(out)
	return out
}

func (in *DynatraceNotificationStatus) DeepCopyInto(out *DynatraceNotificationStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DynatraceNotificationSpec) DeepCopyInto(out *DynatraceNotificationSpec) { *out = *in }
func (in *SecretRef) DeepCopyInto(out *SecretRef)                                   { *out = *in }
