---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-operator
  namespace: sre-tools

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-operator
subjects:
  - kind: ServiceAccount
    name: dynatrace-operator
    namespace: sre-tools
