apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - cmp-configmap.yaml
  - external-secrets.yaml

patches:
  - target:
      kind: Deployment
      name: argocd-repo-server
    path: repo-server-patch.yaml
